export const paintingHouses = [
         {
           id: 1,
           title: "House By The Park",
           imgBefore: "images/painting-1.jpg",
           imgAfter: "images/painting-1a.jpg",
           address: "",
           description: "Wall",
         },
         {
           id: 2,
           title: "7-Floor Building",
           imgBefore: "images/painting-1.jeg",
           imgAfter: "images/painting-1a.jpg",
           address: "",
           description: "House Painting",
         },
         {
           id: 3,
           title: "Church of Calvary",
           imgBefore: "images/painting-1.jpg",
           imgAfter: "images/painting-1a.jpg",
           address: "",
           description: "Hall Painting",
         },
         {
           id: 4,
           title: "University Of Canada",
           imgBefore: "images/painting-1.jpg",
           imgAfter: "images/painting-1a.jpg",
           address: "",
           description: "Dinning RoomPainting",
         },
         {
           id: 5,
           title: "University Of Canada",
           imgBefore: "images/painting-1.jpg",
           imgAfter: "images/painting-1a.jpg",
           address: "",
           description: "Bathroom Painting",
         },

         {
           id: 6,
           title: "University Of Canada",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Classroom Painting",
         },

         {
           id: 6,
           title: "University Of Canada",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Cafeteria",
         },

         {
           id: 7,
           title: "7-Floor Building",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Kitchen",
         },
         {
           id: 8,
           title: "7-Floor Building",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Bathroom",
         },

         {
           id: 9,
           title: "7-Floor Building",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "office",
         },
         {
           id: 10,
           title: "7-Floor Building",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Bedroom",
         },
         {
           id: 11,
           title: "7-Floor Building",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Bedroom",
         },
         {
           id: 12,
           title: "7-Floor Building",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Hall",
         },
         {
           id: 13,
           title: "7-Floor Building",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Bathroom",
         },
         {
           id: 14,
           title: "House By The Park",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Balcony",
         },
         {
           id: 15,
           title: "House By The Park",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Basement",
         },
         {
           id: 16,
           title: "House By The Park",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Roof",
         },
         {
           id: 16,
           title: "House By The Park",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Garage",
         },
         {
           id: 16,
           title: "7-Floor Building",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Roof",
         },
         {
           id: 16,
           title: "7-Floor Building",
           imgBefore: "images/painting-2.jpg",
           imgAfter: "images/painting-2a.png",
           address: "",
           description: "Garage",
         },
       ];
